// data.js
const data = {
  players: [
    {
      "name": "LeBron James",
      "position": "Forward",
      "minutes_played": 35,
      "points": 28,
      "assists": 8,
      "tot_rebounds": 7,
      "off_rebounds": 1,
      "def_rebounds": 6,
      "fg_made": 11,
      "fg_attempted": 21,
      "fg_percent": 52.4,
      "threes_made": 2,
      "threes_attempted": 5,
      "threes_percent": 40,
      "ft_made": 4,
      "ft_attempted": 6,
      "ft_percent": 66.7
    },
    {
      "name": "Stephen Curry",
      "position": "Guard",
      "minutes_played": 36,
      "points": 30,
      "assists": 6,
      "tot_rebounds": 5,
      "off_rebounds": 1,
      "def_rebounds": 4,
      "fg_made": 10,
      "fg_attempted": 20,
      "fg_percent": 50,
      "threes_made": 6,
      "threes_attempted": 13,
      "threes_percent": 46.2,
      "ft_made": 4,
      "ft_attempted": 4,
      "ft_percent": 100
    },
    {
      "name": "Giannis Antetokounmpo",
      "position": "Forward",
      "minutes_played": 37,
      "points": 27,
      "assists": 6,
      "tot_rebounds": 12,
      "off_rebounds": 3,
      "def_rebounds": 9,
      "fg_made": 10,
      "fg_attempted": 17,
      "fg_percent": 58.8,
      "threes_made": 1,
      "threes_attempted": 3,
      "threes_percent": 33.3,
      "ft_made": 6,
      "ft_attempted": 10,
      "ft_percent": 60
    },
    {
      "name": "Kevin Durant",
      "position": "Forward",
      "minutes_played": 34,
      "points": 26,
      "assists": 5,
      "tot_rebounds": 7,
      "off_rebounds": 2,
      "def_rebounds": 5,
      "fg_made": 9,
      "fg_attempted": 18,
      "fg_percent": 50,
      "threes_made": 3,
      "threes_attempted": 7,
      "threes_percent": 42.9,
      "ft_made": 5,
      "ft_attempted": 6,
      "ft_percent": 83.3
    },
    {
      "name": "Kawhi Leonard",
      "position": "Forward",
      "minutes_played": 33,
      "points": 24,
      "assists": 4,
      "tot_rebounds": 6,
      "off_rebounds": 1,
      "def_rebounds": 5,
      "fg_made": 8,
      "fg_attempted": 17,
      "fg_percent": 47.1,
      "threes_made": 2,
      "threes_attempted": 5,
      "threes_percent": 40,
      "ft_made": 6,
      "ft_attempted": 8,
      "ft_percent": 75
    },
    {
      "name": "James Harden",
      "position": "Guard",
      "minutes_played": 37,
      "points": 29,
      "assists": 10,
      "tot_rebounds": 8,
      "off_rebounds": 2,
      "def_rebounds": 6,
      "fg_made": 10,
      "fg_attempted": 22,
      "fg_percent": 45.5,
      "threes_made": 4,
      "threes_attempted": 11,
      "threes_percent": 36.4,
      "ft_made": 5,
      "ft_attempted": 6,
      "ft_percent": 83.3
    },
    {
      "name": "Joel Embiid",
      "position": "Center",
      "minutes_played": 36,
      "points": 30,
      "assists": 4,
      "tot_rebounds": 14,
      "off_rebounds": 3,
      "def_rebounds": 11,
      "fg_made": 12,
      "fg_attempted": 20,
      "fg_percent": 60,
      "threes_made": 2,
      "threes_attempted": 4,
      "threes_percent": 50,
      "ft_made": 4,
      "ft_attempted": 5,
      "ft_percent": 80
    },
    {
      "name": "Anthony Davis",
      "position": "Forward",
      "minutes_played": 32,
      "points": 22,
      "assists": 3,
      "tot_rebounds": 9,
      "off_rebounds": 2,
      "def_rebounds": 7,
      "fg_made": 8,
      "fg_attempted": 16,
      "fg_percent": 50,
      "threes_made": 1,
      "threes_attempted": 3,
      "threes_percent": 33.3,
      "ft_made": 5,
      "ft_attempted": 7,
      "ft_percent": 71.4
    },
    {
      "name": "Luka Dončić",
      "position": "Guard",
      "minutes_played": 38,
      "points": 27,
      "assists": 9,
      "tot_rebounds": 8,
      "off_rebounds": 2,
      "def_rebounds": 6,
      "fg_made": 10,
      "fg_attempted": 22,
      "fg_percent": 45.5,
      "threes_made": 4,
      "threes_attempted": 10,
      "threes_percent": 40,
      "ft_made": 3,
      "ft_attempted": 5,
      "ft_percent": 60
    }
  ]
};

export default data;
